#sudo: false
#language: node_js
#node_js:
#- '6.0'
#cache:
#  directories:
#  - node_modules
#branches:
#  only:
#  - master
#notifications:
#  email: false
#before_script:
#- npm install
#script:
#- npm run --silent build
#after_success:
#- bash deploy.sh
#env:
#  global:
#  - GH_USER: sensein
#  - GH_REPO: voice-study
#  - secure: M4XnFnHpaMAwzx2JDwyRuHM/i7P+G4lGpNEbcKY/ub7H7/XzM2UvYHumZXW5AnGOJGFhEltzdO88KESU5xDqlf5bgOJkdqUqLk1g2t5/QfTW1D8liCpJFWHpF+xTopW7oJTEXavhUArEBAIDaJGn8+A4GMw3F8fDgGYNl2peg7pU+Y6Qk/27ee1Ia5Ly1Og6byqsbH0opve+zjvswCwlEDxhkN6HuaQKl6pxkHEg0YVbdDCwtPW+hEnlL3xmsOaA3aSYpsmfH/pNZgFiWiDGj961W2K5AGidNPwVQFNd0b0qgL/eOzuZ34R2zGnvW1qrtYT89n3GQw02odTHHbZyveaH62gvBc1XdVhSB7IcEBSLnF160S7LrGqfkwvA3Eu6FqimRBrS+abPiAY+0OuNgjO66hdYrlbjKd5CSeHV3/57trv+ZqhHJa/Gy7I2G0kjCq2j0HgLp9OupTredRSPsOzPtDfRweWVuEBmoCClVlLIQQ45tiW2kwxKyLKkWWqtLcnLy3L+S0uuE3Bh3Y9ENuHL8VWAMJM79GWl8CFxiI0isjWPKpRl2gpEASOaZlfmMT2gxZslBazJEJp7nMbpiWqMGLQ9IMi2Emmu4mUM6osJNEAKs4XzBN9P5Xn7Fimx4kBi3gj5TNxffln0rdj8U2mz1QTfhFfCJ8/NqQdkzdM=

language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master

